version: '2'

services:
    mariadb:
        image: docker.io/bitnami/mariadb:10.6
        ports:
            - '8109:3306'
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=room_booking
            - MARIADB_DATABASE=room_booking

    myapp:
        image: docker.io/bitnami/laravel:9
        ports:
            - '8009:8000'
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USERNAME=room_booking
            - DB_DATABASE=room_booking
        volumes:
            - './:/app'
        depends_on:
            - mariadb
